name: Deploy-Staging

on:
  push:
    branches:
      - 'develop'

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 10.18.1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn deploy:staging:all
