version: 2
endpoint: https://staging-eaw3qk5meq-uc.a.run.app/
admin_secret: stagingadminsecret
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:5003/services
