name: Deploy-Staging

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 10.18.1
      - run: yarn --frozen-lockfile
      - run: yarn global add firebase-tools
      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          HASURA_STAGING_ADMIN_SECRET: ${{ secrets.HASURA_STAGING_ADMIN_SECRET }}
        run: yarn deploy:staging:hasura --verbose
