name: Deploy-Staging

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 10.18.1
      - run: yarn --frozen-lockfile --verbose
      - run: yarn global add firebase-tools --verbose
      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn deploy:staging:all --verbose
